# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skillimage/')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
