# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cmail', models.EmailField(max_length=50)),
                ('cquery', models.TextField(max_length=1000)),
            ],
        ),
    ]
